### ISSUE TITLE
Use clap feature: suggestions

### ISSUE THREAD

**Issue by matthiasbeyer** [matthiasbeyer/imag#539]
Would be awesome to use the clap feature "suggestions".

I guess we can do this and we would not need the unstable compiler for this. One problem is, though, that you cannot enable this by simply calling a function on some `App` object or something like this - you have to use the package option.

Because of this I think about creating a wrapper package for clap (only for internal use of course) which simply depends on clap and re-publishes its interface, but configures clap the way we want it in imag.

I'm not sure whether this is a good idea or even doable... maybe @kbknapp can tell me whether this is doable?

The other option would be to set the clap features in _every single_ `Cargo.toml` - which would be really noisy actually:

``` toml
[dependencies.clap]
version = "2"
default-features = false

# Cherry-pick the features you'd like to use
features = [ "suggestions", "color" ]
```

vs.

``` toml
[dependencies.imag-wrapper-clap]
path = "../ext/imag-clap"
```

or something like this.
